-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY; CREATE POLICY anon_insert_contact_messages ON contact_messages FOR INSERT WITH CHECK (true); CREATE POLICY admins_select_contact_messages ON contact_messages FOR SELECT USING (true);
